const TYPESDEPENDENCIES = {
    db: Symbol.for('db'),
    dbTms: Symbol.for('dbTms'),
    Axios: Symbol.for('Axios'),
    RedisRepository: Symbol.for('RedisRepository'),
    RedisClient: Symbol.for('RedisClient'),
    TokenService: Symbol.for('TokenService'),
    EnviosRepository: Symbol.for('PostgresEnviosRepository'),
    EnviosDomainService: Symbol.for('EnviosDomainService'),
    EquiposDomainService: Symbol.for('EquiposDomainService'),
    EquiposRepository: Symbol.for('PostgresEquiposRepository'),
    CondicionesDomainService: Symbol.for('CondicionesDomainService'),
    EventosRepository: Symbol.for('PostgresEventosRepository'),
    GeolocalizacionDomainService: Symbol.for('GeolocalizacionDomainService'),
    OrdenamientoPorTraficoStrategy: Symbol.for('OrdenamientoPorTraficoStrategy'),
    OrdenamientoPorClimaStrategy: Symbol.for('OrdenamientoPorClimaStrategy'),
    OrdenamientoPorEventosStrategy: Symbol.for('OrdenamientoPorEventosStrategy'),
    EstrategiaFactory: Symbol.for('EstrategiaFactory'),
    OrdenadorRutas: Symbol.for('OrdenadorRutas'),
    RutasRepository: Symbol.for('PostgresRutasRepository'),
    PubSub: Symbol.for('PubSub'),
    PublisherPubsub: Symbol.for('PublisherPubsub'),
}

export default TYPESDEPENDENCIES
