name: Cloud Run Deployment Flow
concurrency: ${{ github.event.repository.name }}-prod
on:
  push:
    branches:
      - 'master'
env:
  SERVICE_NAME: yohan-cm-tms-ms
  PROJECT_ID: ${{ secrets.PROJECT_ID_PROD }}
  REGION: us-central1
  ENV_FILE: env/main.env
  ENV: prod
  HOST: apiv2.coordinadora.com
  MEMORY: 512Mi
  CPU: 1
  ALLOW_UNAUTHENTICATED: true
  DOMAIN: tms
  SUB_DOMAIN: example

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and deploy to Cloud Run
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - uses: actions/setup-node@v4
        with:
          node-version: '>=20.9.0'
          
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          
      - name: Install and Build
        uses: ./.github/actions/build
        
      - name: Build tests
        uses: ./.github/actions/quality

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          
      - name: Authorize Docker push
        run: gcloud auth configure-docker
        
      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .
          docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          
      - name: Create ENV File
        run: |
          echo "PROJECT_ID=${{ env.PROJECT_ID }}" >> ${{ env.ENV_FILE }}
          echo "SERVICE_NAME=${{ env.SERVICE_NAME }}" >> ${{ env.ENV_FILE }}
          echo "HOST=${{ env.HOST }}" >> ${{ env.ENV_FILE }}
          echo "DOMAIN=${{ env.DOMAIN }}" >> ${{ env.ENV_FILE }}
          cp ${{ env.ENV_FILE }} .env
          
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ env.SERVICE_NAME }}
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          region: ${{ env.REGION }}
          flags: |
            --memory=${{ env.MEMORY }}
            --cpu=${{ env.CPU }}
            --platform=managed
            --allow-unauthenticated
            --set-env-vars=ENV=${{ env.ENV }},DOMAIN=${{ env.DOMAIN }}
            
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}